let varer = [
    {
      Vare: "Traktor",
      UtleierNavn: "Herman",
      UtleidAv: "Kristoffer",
      LengdeLeid: "5/5/25",
      Returnert: true,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "Hettegenser",
      UtleierNavn: "ibrahim",
      UtleidAv: "Kristoffer",
      LengdeLeid: "6/2/27",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
    {
      Vare: "ganan",
      UtleierNavn: "Algirdas",
      UtleidAv: "Kristoffer",
      LengdeLeid: "4/7/25",
      Returnert: false,
    },
  ];

  varer.push({
    Vare: "gernann123",
    UtleierNavn: "hernanan",
    UtleidAv: "ibanananan",
    LengdeLeid: "5/8/10000002",
    Returnert: false,
  })